# Generated by Django 5.2.3 on 2025-06-16 16:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.date(2025, 6, 16),
                verbose_name="Дата оплаты",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Наличные"), ("Non_cash", "Безналичные")],
                default=datetime.date(2025, 6, 16),
                max_length=50,
                verbose_name="Способ оплаты",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
