# Generated by Django 5.2.3 on 2025-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Цена курса"
            ),
        ),
    ]
